# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import aiva_ros_bridge_pb2 as proto_dot_aiva__ros__bridge__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/aiva_ros_bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AivaRosBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRobots = channel.unary_unary(
                '/AivaRosBridge/SendRobots',
                request_serializer=proto_dot_aiva__ros__bridge__pb2.RobotDefinitionsMessage.SerializeToString,
                response_deserializer=proto_dot_aiva__ros__bridge__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRequests = channel.stream_stream(
                '/AivaRosBridge/GetRequests',
                request_serializer=proto_dot_aiva__ros__bridge__pb2.RobotResponse.SerializeToString,
                response_deserializer=proto_dot_aiva__ros__bridge__pb2.RobotRequest.FromString,
                _registered_method=True)


class AivaRosBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRobots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequests(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AivaRosBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRobots': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRobots,
                    request_deserializer=proto_dot_aiva__ros__bridge__pb2.RobotDefinitionsMessage.FromString,
                    response_serializer=proto_dot_aiva__ros__bridge__pb2.Empty.SerializeToString,
            ),
            'GetRequests': grpc.stream_stream_rpc_method_handler(
                    servicer.GetRequests,
                    request_deserializer=proto_dot_aiva__ros__bridge__pb2.RobotResponse.FromString,
                    response_serializer=proto_dot_aiva__ros__bridge__pb2.RobotRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AivaRosBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AivaRosBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AivaRosBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRobots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AivaRosBridge/SendRobots',
            proto_dot_aiva__ros__bridge__pb2.RobotDefinitionsMessage.SerializeToString,
            proto_dot_aiva__ros__bridge__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRequests(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/AivaRosBridge/GetRequests',
            proto_dot_aiva__ros__bridge__pb2.RobotResponse.SerializeToString,
            proto_dot_aiva__ros__bridge__pb2.RobotRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
