# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/aiva_ros_bridge.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto/aiva_ros_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/aiva_ros_bridge.proto\"\x07\n\x05\x45mpty\",\n\x16RobotDefinitionMessage\x12\x12\n\nip_address\x18\x01 \x01(\t\"G\n\x17RobotDefinitionsMessage\x12,\n\x0b\x64\x65\x66initions\x18\x01 \x03(\x0b\x32\x17.RobotDefinitionMessage\"v\n\x0cRobotRequest\x12)\n\x0cplan_request\x18\x01 \x01(\x0b\x32\x11.RobotPlanRequestH\x00\x12/\n\x0f\x65xecute_request\x18\x02 \x01(\x0b\x32\x14.RobotExecuteRequestH\x00\x42\n\n\x08requests\" \n\rRobotResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x10RobotPlanRequest\x12\x11\n\tplan_name\x18\x01 \x01(\t\"(\n\x13RobotExecuteRequest\x12\x11\n\tplan_name\x18\x01 \x01(\t2u\n\rAivaRosBridge\x12\x30\n\nSendRobots\x12\x18.RobotDefinitionsMessage\x1a\x06.Empty\"\x00\x12\x32\n\x0bGetRequests\x12\x0e.RobotResponse\x1a\r.RobotRequest\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.aiva_ros_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_ROBOTDEFINITIONMESSAGE']._serialized_start=40
  _globals['_ROBOTDEFINITIONMESSAGE']._serialized_end=84
  _globals['_ROBOTDEFINITIONSMESSAGE']._serialized_start=86
  _globals['_ROBOTDEFINITIONSMESSAGE']._serialized_end=157
  _globals['_ROBOTREQUEST']._serialized_start=159
  _globals['_ROBOTREQUEST']._serialized_end=277
  _globals['_ROBOTRESPONSE']._serialized_start=279
  _globals['_ROBOTRESPONSE']._serialized_end=311
  _globals['_ROBOTPLANREQUEST']._serialized_start=313
  _globals['_ROBOTPLANREQUEST']._serialized_end=350
  _globals['_ROBOTEXECUTEREQUEST']._serialized_start=352
  _globals['_ROBOTEXECUTEREQUEST']._serialized_end=392
  _globals['_AIVAROSBRIDGE']._serialized_start=394
  _globals['_AIVAROSBRIDGE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
